# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad7e30c9d6afb92669bc8d3bbf7d9bdaf3fcae5477e7fcfadd9fe5919181c3ec701fe2f1f72f2244128aac8ca77c44ef1daeac1dc9755dafeecb8f5f4bee6045

test:
  secret_key_base: 5ebff88304be23d182ae5990d4bb5354694a56a5137e8828a7c5db184a5b8de97f67462365aa07cf11da841482e68935ea92ef859a497dba494fcbcf6b5e49dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
